### ISSUE TITLE
Build Chimera as Part of Hyperscan

### ISSUE THREAD

**Issue by simpleyetawesomeprojects** [gliwka/hyperscan-java-native#29]
Hello @gliwka , Thank you for your efforts in creating this library.  

Hperscan is excellent, but it does not have full support for PCRE syntax, and Chimera which is included in hyperscan source has full support for PCRE syntax. Chimera is a hybrid of Hyperscan and PCRE.

Per the documentation, http://intel.github.io/hyperscan/dev-reference/chimera.html,

_"Building Hyperscan will automatically generate Chimera library. Currently only static library is supported for Chimera, so please use static build type when configure CMake build options"_

 Could you please let me know if there is any plan to incorporate changes to build Chimera?

I have been experimenting with building the changes in the below PR, I'm a newbie to javacpp and unable to figure out what needs to be done to make Chimera work.

The PR includes a Chimera Test example class, when I run it, I see the below error. How can I resolve this error? Any help is greatly appreciated.

`dyld: lazy symbol binding failed: Symbol not found: _ch_compile_multi
  Referenced from: /Users/aaa/.javacpp/cache/native-5.4.0-1.1.0-SNAPSHOT-macosx-x86_64.jar/com/gliwka/hyperscan/jni/macosx-x86_64/libjnihyperscan.dylib
  Expected in: flat namespace

dyld: Symbol not found: _ch_compile_multi
  Referenced from: /Users/aaa/.javacpp/cache/native-5.4.0-1.1.0-SNAPSHOT-macosx-x86_64.jar/com/gliwka/hyperscan/jni/macosx-x86_64/libjnihyperscan.dylib
  Expected in: flat namespace`

here is the PR with the changes to build Chimera
https://github.com/simpleyetawesomeprojects/hyperscan-java-native/pull/1/files

**Comment by gliwka** [comment]
Shipping Chimera would require static linking, which will result in a licensing issue making me unable to distribute the binaries.

The recent version of hyperscan-java implements the PatternFilter, providing the same functionality as Chimera, just native to the JDK.
